"""Add OCRResult and OCRTextRegion models

Revision ID: d3eca8aba13e
Revises: a1c41a0e71ad
Create Date: 2026-09-04 02:50:01.916044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3eca8aba13e'
down_revision: Union[str, None] = 'a1c41a0e71ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_full_text', sa.String(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_table('ocr_text_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ocr_result_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_text_regions')
    op.drop_table('ocr_results')
    # ### end Alembic commands ###
